[TASK][CERT-125] Remove readonly property on datepicker fields
TYPO3GmbH/symfony-template-bundle pull request #212
Opened 2022-06-13 12:48 UTC by tomasnorre

2022-06-13 13:08 UTC, tomasnorre commented
OK. Then we misunderstood each other completely. I'll look at it again.

2022-06-13 13:39 UTC, benjaminkott requested changes
Please make sure to reset all overwritten properties

https://github.com/twbs/bootstrap/blob/v5.1.3/scss/forms/_form-control.scss#L69-L72

2022-06-14 04:42 UTC, tomasnorre commented
I'm unsure regarding the `opacity: 1` as `1` is the default value for opacity. 
Please let me know if I should change that too. 

https://github.com/twbs/bootstrap/blob/v5.1.3/scss/forms/_form-control.scss#L69-L72

2022-06-14 09:38 UTC, benjaminkott requested changes
frocus border is still mismatching

2022-06-15 07:42 UTC, benjaminkott commented on assets/css/components/_datepicker.scss
> +.flatpickr-input[readonly] {
try `.flatpickr-input[readonly]:not([disabled])`

2022-06-15 09:58 UTC, tomasnorre commented on assets/css/components/_datepicker.scss
> +.flatpickr-input[readonly] {
That works too.

2022-06-15 12:46 UTC, benjaminkott approved these changes

2022-06-15 12:59 UTC, merged